[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" # ou a versão que você usa no projeto
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
